FROM postgres:latest

RUN apt-get update && apt-get install -y \
    git \
    postgresql-server-dev-all \
    build-essential
    && rm -rf /var/lib/apt/lists/*

RUN git clone --branch v0.8.0 https://github.com/pgvector/pgvector.git /pgvector \
    && cd /pgvector \
    && make install

COPY init.sql /docker-entrypoint-initdb.d/
