services:
  api: &main_app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: app:${APP_VERSION:-latest}
    restart: always
    env_file:
      - .env
    environment:
      APP_HOST: 0.0.0.0

      # database settings
      APP_DB_HOST: "localhost"
      APP_DB_PORT: "5432"
      APP_DB_BASE: "postgres"
      APP_DB_USER: "postgres"
      APP_DB_PASS: "password"
    volumes:
      - app-db-data:/db_data/

  migrator:
    image: app:${APP_VERSION:-latest}
    restart: "no"
    command: alembic upgrade head
    environment:
      # database settings
      APP_DB_HOST: "localhost"
      APP_DB_PORT: "5432"
      APP_DB_BASE: "postgres"
      APP_DB_USER: "postgres"
      APP_DB_PASS: "password"
    volumes:
      - app-db-data:/db_data/



volumes:
  app-db-data:
    name: app-db-data
