"""Nullable -> False for Embeddings

Revision ID: 2ca97e582301
Revises: a1eef51fdab7
Create Date: 2024-11-18 20:47:13.520079

"""

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy.vector import VECTOR

# revision identifiers, used by Alembic.
revision = "2ca97e582301"
down_revision = "a1eef51fdab7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "embeddings",
        "vector",
        existing_type=VECTOR(dim=512),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "embeddings",
        "vector",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=512),
        nullable=True,
    )
    # ### end Alembic commands ###
