"""Impove embedings

Revision ID: ae87ca4c04dd
Revises: ed69f420bc7b
Create Date: 2024-11-18 02:58:12.797613

"""

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy.vector import VECTOR


# revision identifiers, used by Alembic.
revision = "ae87ca4c04dd"
down_revision = "ed69f420bc7b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "embeddings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("vector", VECTOR(dim=512), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("embeddings")
    # ### end Alembic commands ###
