"""Nullable -> true for Embeddings

Revision ID: a1eef51fdab7
Revises: ae87ca4c04dd
Create Date: 2024-11-18 20:40:40.642836

"""

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy.vector import VECTOR

# revision identifiers, used by Alembic.
revision = "a1eef51fdab7"
down_revision = "ae87ca4c04dd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "embeddings",
        "vector",
        existing_type=VECTOR(dim=512),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "embeddings",
        "vector",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=512),
        nullable=False,
    )
    # ### end Alembic commands ###
