"""rename embedding -> embeddings

Revision ID: 2448a1ac599c
Revises: 6cbb8fcede2d
Create Date: 2024-11-11 08:31:59.461339

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2448a1ac599c"
down_revision = "6cbb8fcede2d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("embeddings", sa.Text(), nullable=True))
    op.drop_column("users", "embedding")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("embedding", sa.TEXT(), nullable=True))
    op.drop_column("users", "embeddings")
    # ### end Alembic commands ###
